[build]
publish = "public"
command = """hugo \
  --source website-cit59x \
  --config website-cit59x/config.toml \
  --themesDir ../.. \
  --theme repo \
 """




#[build]
#publish = "public"
#command = "hugo --gc --minify --themesDir ../.."
# --baseURL https://some-netlify-url.com"

#[build]
 # publish = "website-cit59x/public"
  #command = "cd exampleSite && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_THEME = "repo"

[context.production.environment]
HUGO_VERSION = "0.65.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.65.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.65.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.65.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

